#!/usr/bin/env bash
set -euo pipefail

# changelog.sh — Generate a structured CHANGELOG.md from git history
# Usage: bash changelog.sh [repo-path]

REPO_DIR="${1:-.}"
cd "$REPO_DIR"

LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
if [ -z "$LAST_TAG" ]; then
  LOG_RANGE="HEAD"
  TAG_LABEL="initial commit"
else
  LOG_RANGE="${LAST_TAG}..HEAD"
  TAG_LABEL="$LAST_TAG"
fi

if ! git log "$LOG_RANGE" --oneline 2>/dev/null | grep -q .; then
  echo "No new commits since $TAG_LABEL."
  exit 0
fi

SECTIONS_ADDED=""
SECTIONS_FIXED=""
SECTIONS_CHANGED=""
SECTIONS_REMOVED=""

while IFS='|' read -r HASH SUBJECT; do
  LOWER=$(echo "$SUBJECT" | tr '[:upper:]' '[:lower:]')
  CATEGORY="Changed"
  if echo "$LOWER" | grep -qE '^(feat|add|create|implement|introduce|new)'; then
    CATEGORY="Added"
  elif echo "$LOWER" | grep -qE '^(fix|patch|correct|hotfix|bug)'; then
    CATEGORY="Fixed"
  elif echo "$LOWER" | grep -qE '^(remove|delete|deprecate|drop|clean)'; then
    CATEGORY="Removed"
  fi

  ENTRY="- ${SUBJECT} (\`${HASH:0:7}\`)"
  if [ "$CATEGORY" = "Added" ]; then SECTIONS_ADDED+="${ENTRY}"$'\n'
  elif [ "$CATEGORY" = "Fixed" ]; then SECTIONS_FIXED+="${ENTRY}"$'\n'
  elif [ "$CATEGORY" = "Removed" ]; then SECTIONS_REMOVED+="${ENTRY}"$'\n'
  else SECTIONS_CHANGED+="${ENTRY}"$'\n'
  fi
done < <(git log "$LOG_RANGE" --format="%H|%s" --reverse)

{
  echo "# Changelog"
  echo ""
  echo "_Generated on $(date '+%Y-%m-%d %H:%M:%S') from commits since \`${TAG_LABEL}\`._"
  echo ""
  [ -n "$SECTIONS_ADDED" ] && echo "## Added" && echo "" && echo "${SECTIONS_ADDED}"
  [ -n "$SECTIONS_FIXED" ] && echo "## Fixed" && echo "" && echo "${SECTIONS_FIXED}"
  [ -n "$SECTIONS_CHANGED" ] && echo "## Changed" && echo "" && echo "${SECTIONS_CHANGED}"
  [ -n "$SECTIONS_REMOVED" ] && echo "## Removed" && echo "" && echo "${SECTIONS_REMOVED}"
  echo "---"
  echo "_Auto-generated by [changelog.sh](CHANGELOG.md)_"
} > CHANGELOG.md

echo "✓ Generated CHANGELOG.md"
